language: python
python: 3.5.2
services:
  - postgresql
before_script:
  - psql -c 'create database ridemywaydb_testing;' -U postgres
script: pep8 app && python -m pytest && coverage run -m pytest && coverage report
after_success: coveralls
